variables:
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:5.2.1'
  - &platforms 'linux/amd64,linux/arm64,linux/riscv64'
  - publish_login: &publish_login
      - registry: https://git.jcm.re
        username:
          from_secret: gitea_package_user
        password:
          from_secret: gitea_package_token

when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  docker:
    image: *buildx_plugin
    settings:
      repo: jcm/cutie-logs
      dockerfile: Dockerfile
      platforms: *platforms
      tags: ["latest", "${CI_COMMIT_SHA}"]
      logins: *publish_login
