variables:
  - &buildx_plugin 'docker.io/woodpeckerci/plugin-docker-buildx:5.2.1'
  - &platforms 'linux/arm64'
  - publish_logins: &publish_logins
      - registry: https://git.jcm.re
        username:
          from_secret: gitea_package_user
        password:
          from_secret: gitea_package_token

when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  docker:
    image: *buildx_plugin
    settings:
      repo: ["jcm/cutie-logs"]
      dockerfile: Dockerfile
      platforms: *platforms
      tag: ["latest", "${CI_COMMIT_SHA}"]
      logins: *publish_logins
